from typing import Any


class Enum:
	def __init__(self, value: int) -> None: ...
	# comparison
	def __eq__(self, other: Any) -> bool: ...
	def __ne__(self, other: Any) -> bool: ...
	def __not__(self, other: Any) -> bool: ...
