from typing import Any


class EnumType: ...
class Enum:
	def __init__(self, value: int) -> None: ...
	@property
	def name(self) -> str: ...
	# FIXME 本来はMoveAssignの右辺によって型が確定。プロパティーとしてのマッピングも正しくはないため、検討が必要
	@property
	def value(self) -> Any: ...
	# comparison
	def __eq__(self, other: Any) -> bool: ...
	def __ne__(self, other: Any) -> bool: ...
	def __not__(self, other: Any) -> bool: ...
