pi: float

def atan2(y: float, x: float) -> float: ...
def cos(radian: float) -> float: ...
def floor(value: float) -> float: ...
def sin(radian: float) -> float: ...
def sqrt(x: float) -> float: ...
