pi: float

def atan2(y: float, x: float) -> float: ...
def cos(radian: float) -> float: ...
def cross(x: list[float], y: list[float]) -> list[float]: ...
def dot(x: list[float], y: list[float]) -> float: ...
def floor(value: float) -> float: ...
def sin(radian: float) -> float: ...
def sqrt(x: float) -> float: ...
