class linalg:
	def norm(self, vector: list[float]) -> float: ...


pi: float


def atan2(y: float, x: float) -> float: ...
def cos(radian: float) -> float: ...
def cross(a: list[float], b: list[float]) -> list[float]: ...
def dot(a: list[float], b: list[float]) -> float: ...
def floor(value: float) -> float: ...
def sin(radian: float) -> float: ...
def sqrt(x: float) -> float: ...
