# XXX 厳密な定義ではないが、実用上は問題ない
environ: dict[str, str]


def getcwd() -> str: ...
def getenv(key: str) -> str | None: ...


class path:
	def exists(self, filepath: str) -> bool: ...
	def join(self, *args: str) -> str: ...
	def dirname(self, filepath: str) -> str: ...
	def basename(self, filepath: str) -> str: ...
	def abspath(self, filepath: str) -> str: ...
