from typing import Any, Generic, TypeVar

T = TypeVar('T')


class Match(Generic[T]):
	@property
	def endpos(self) -> int: ...


class Pattern(Generic[T]): ...


def compile(pattern: str, flags: int = 0) -> Pattern[str]: ...
def findall(pattern: str, string: str, flags: int = 0) -> list[Any]: ...
def search(pattern: str, string: str, flags: int = 0) -> Match[str] | None: ...
def fullmatch(pattern: str, string: str, flags: int = 0) -> Match[str] | None: ...
def split(pattern: str, string: str, maxsplit: int = 0, flags: int = 0) -> list[str] | Any: ...
def sub(pattern: str, replace: str, string: str, count: int = 0, flags: int = 0) -> list[str] | Any: ...
