class Any: ...
class Callable: ...
class Generic: ...
class NamedTuple: ...
class Sequence: ...
class TypeAlias: ...
class TypeVar: ...

# FIXME 警告は一旦無視(循環参照を解決できないため)
T = TypeVar('T')


# FIXME castの定義のため必要。classes側の定義は消さないこと
# FIXME __actual__の未定義エラーは解決方法がないため一旦無視
@__actual__('type')
class Type(Generic[T]): ...


class Iterator(Generic[T]):
	def __next__(self) -> T: ...


def cast(to: type[T], value: Any) -> T: ...
