class Any: ...
class Callable: ...
class Generic: ...
class Sequence: ...
class TypeAlias: ...
class TypeVar: ...

# FIXME 警告は一旦無視(循環参照を解決できないため)
T_Value = TypeVar('T_Value')


class Iterator(Generic[T_Value]):
	def __next__(self) -> T_Value: ...


# FIXME Reflectionsがクラスの型と変数の型を区別できないため、一旦typeは除外する
# FIXME def cast(to: type[T_Value], value: Any) -> T_Value: ...
def cast(to: T_Value, value: Any) -> T_Value: ...
