from typing import TypeAlias


class char(int): ...
class byte(int): ...
class int8(int): ...
class uint8(int): ...
class int32(int): ...
class int64(int): ...
class uint32(int): ...
class uint64(int): ...
class double(float): ...
void: TypeAlias = object
