from typing import TypeAlias

# String XXX タイプヒントで型名が必要なためクラスとして実装

class char(str): ...
class wchar_t(str): ...

# Digit XXX タイプヒントで型名が必要なためクラスとして実装

class byte(int): ...
class int8(int): ...
class uint8(int): ...
class int32(int): ...
class int64(int): ...
class uint32(int): ...
class uint64(int): ...

# Decimal XXX タイプヒントで型名が必要なためクラスとして実装

class double(float): ...

# Object

# XXX 本質的には正しくないが、void*としてのみ使用するため、これによって無駄なキャストを軽減
void: TypeAlias = object
