pi: float


class linalg:
	@classmethod
	def norm(cls, vector: list[float]) -> float: ...


class random:
	@classmethod
	def seed(cls, value: int) -> None: ...
	@classmethod
	def rand(cls) -> float: ...


def atan2(y: float, x: float) -> float: ...
def cos(radian: float) -> float: ...
def cross(a: list[float], b: list[float]) -> list[float]: ...
def dot(a: list[float], b: list[float]) -> float: ...
def floor(value: float) -> float: ...
def power(value: float, exponent: float) -> float: ...
def sin(radian: float) -> float: ...
def sqrt(x: float) -> float: ...
def tan(radian: float) -> float: ...
def trunc(value: float) -> float: ...
