class Annotated: ...
class Any: ...
class ClassVar: ...
class ContextManager: ...
class ForwardRef: ...
class Generic: ...
class Literal: ...
class NamedTuple: ...
class Protocol: ...
class TypeVar: ...
class TypeAlias: ...
class TypeVarTuple: ...
class TypedDict: ...
class Union: ...


class IO:
	def __enter__(self) -> 'IO': ...
	# XXX 実装が無くても実用上は問題ないため一旦省略
	# def __exit__(self, exc_type, exc, tb) -> None: ...


class ParamSpec:
	# XXX ParamSpecArgs/ParamSpecKwargsへの変更を検討
	class args: ...
	class kwargs: ...


class TypeIs[T]: ...


def final[T](decorated: T) -> T: ...
def override[T](decorated: T) -> T: ...
def overload[T](decorated: T) -> T: ...
def cast[T](to: type[T], value: Any) -> T: ...
def get_origin[T](t: Any) -> Any: ...


# FIXME 警告は一旦無視
Self = TypeVar('Self')
