[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tranp"
version = "0.9.0"
description = "A language-agnostic source-to-source transpiler framework."
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
license-files = ["LICENSE"]

[tool.ruff]
line-length = 320

[tool.ruff.lint]
select = ["I"]
ignore = ["ALL"]

[tool.ruff.format]
exclude = ["**/*.py"]
