[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tranp"
version = "0.9.0"
description = "A language-agnostic source-to-source transpiler framework."
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
license-files = ["LICENSE"]
keywords = [
  "transpiler",
  "transpilation",
  "source-to-source",
  "compiler",
  "code generation",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: C++",
  "Topic :: Software Development :: Compilers",
]
