class Any: ...
class Callable: ...
class Generic: ...
class Sequence: ...
class TypeAlias: ...
class TypeVar: ...

# FIXME 警告は一旦無視
T_Seq = TypeVar('T_Seq')

class Iterator(Generic[T_Seq]):
	def __next__(self) -> T_Seq:
		...
