grammar: data/grammar.lark
trans_mapping: data/i18n.yml
template_dirs:
  - data/cpp/template
input_globs: []
exclude_patterns: []
output_dirs:
  - ./
output_language: cpp:h
env:
  transpiler:
    include_dirs: []
  view:
    immutable_param_types:
      - std::string
      - std::vector
      - std::map
      - std::function
