class Callable: ...
class Sequence: ...
# XXX ItemsView用の定義。実際は存在しない点に注意
class Pair[T_Key, T_Value]: ...


class Iterator[T]:
	def __next__(self) -> T: ...


class ItemsView[T_Key, T_Value]:
	def __next__(self) -> Iterator[Pair[T_Key, T_Value]]: ...
