// entry
entry := (exp)+ "\n"

// terminal
bool := /False|True/
int := /[1-9]\d*/
float := /(0|[1-9]\d*)[.]\d+/
str := /'[^']*'|"[^"]*"/
none := "None"
name := /[a-zA-Z_]\w*/

// expression
var := name
?exp := primary

// primary
?primary := relay | invoke | indexer | atom
relay := primary "." name
invoke := primary "(" [args] ")"
indexer := primary "[" exp "]"
?atom := var | bool | none | str | int | float

// element
args := exp ("," exp)*
