// entrypoint
entry := (rule)+

// rule
rule := symbol ["[" unwrap "]"] ":=" expr "\n"

// expression
expr[1] := terms_or
terms_or[1] := terms ("|" terms)*
terms[1] := term (term)*
term[1] := symbol | string | regexp | expr_opt | expr_rep
expr_opt := "[" expr "]"
expr_rep := "(" expr ")" [repeat]

// terminal
symbol := /[a-zA-Z_]\w*/
string := /"[^"]+"/
regexp := /[\/].+[\/]/
repeat := /[*+?]/
unwrap := /[1*]/
